on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  pyinstaller-build-with-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.15.0'
          spec: 'lyrics_book_maker.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: '歌词本生成器-Windows'
          options: -F

  pyinstaller-build-with-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.15.0'
          spec: 'lyrics_book_maker.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: '歌词本生成器-Linux'
          options: -F